<a href="https://colab.research.google.com/github/akheel8743/Brolly1/blob/main/Titanic_Survivors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('titanic.csv',sep =',')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [18]:
df.dtypes

PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex              object
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin            object
Embarked         object
Travel alone      uint8
dtype: object

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [24]:
df['Travel alone'] = np.where((df['SibSp'] + df['Parch'])> 0,0,1).astype('uint8')

In [25]:
df1 =df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin'],axis = 1)

In [26]:
df1.isna().sum()

Survived        0
Pclass          0
Sex             0
Age             0
Fare            1
Embarked        0
Travel alone    0
dtype: int64

In [27]:
df['Age'].fillna(df['Age'].median(skipna = True),inplace = True)

<ipython-input-27-f65c6f59cf05>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(skipna = True),inplace = True)

In [28]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Travel alone
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,1
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,1
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0

In [30]:
df_titanic = pd.get_dummies(df1,columns = ['Pclass','Sex', 'Embarked'],drop_first = True)

In [32]:
df_titanic.head()

,Survived,Age,Fare,Travel alone,Pclass_2,Pclass_3,Sex_male,Embarked_Q,Embarked_S
0,0,34.5,7.8292,1,False,True,True,True,False
1,1,47.0,7.0000,0,False,True,False,False,True
2,0,62.0,9.6875,1,True,False,True,True,False
3,0,27.0,8.6625,1,False,True,True,False,True
4,1,22.0,12.2875,0,False,True,False,False,True

In [33]:
X = df_titanic.drop('Survived',axis = 1)
y = df_titanic['Survived']

In [34]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [35]:
trans_MM = MinMaxScaler()
trans_SS = StandardScaler()

In [36]:
df_MM = trans_MM.fit_transform(X)
pd.DataFrame(df_MM)

            0         1    2    3    4    5    6    7
0    0.452723  0.015282  1.0  0.0  1.0  1.0  1.0  0.0
1    0.617566  0.013663  0.0  0.0  1.0  0.0  0.0  1.0
2    0.815377  0.018909  1.0  1.0  0.0  1.0  1.0  0.0
3    0.353818  0.016908  1.0  0.0  1.0  1.0  0.0  1.0
4    0.287881  0.023984  0.0  0.0  1.0  0.0  0.0  1.0
..        ...       ...  ...  ...  ...  ...  ...  ...
413  0.353818  0.015713  1.0  0.0  1.0  1.0  0.0  1.0
414  0.512066  0.212559  1.0  0.0  0.0  0.0  0.0  0.0
415  0.505473  0.014151  1.0  0.0  1.0  1.0  0.0  1.0
416  0.353818  0.015713  1.0  0.0  1.0  1.0  0.0  1.0
417  0.353818  0.043640  0.0  0.0  1.0  1.0  0.0  0.0

[418 rows x 8 columns]

In [37]:
df_SS = trans_SS.fit_transform(X)
pd.DataFrame(df_SS)

,0,1,2,3,4,5,6,7
0,0.386231,-0.497811,0.807573,-0.534933,0.957826,0.755929,2.843757,-1.350676
1,1.371370,-0.512660,-1.238278,-0.534933,0.957826,-1.322876,-0.351647,0.740370
2,2.553537,-0.464532,0.807573,1.869391,-1.044031,0.755929,2.843757,-1.350676
3,-0.204852,-0.482888,0.807573,-0.534933,0.957826,0.755929,-0.351647,0.740370
4,-0.598908,-0.417971,-1.238278,-0.534933,0.957826,-1.322876,-0.351647,0.740370
...,...,...,...,...,...,...,...,...
413,-0.204852,-0.493856,0.807573,-0.534933,0.957826,0.755929,-0.351647,0.740370
414,0.740881,1.312180,0.807573,-0.534933,-1.044031,-1.322876,-0.351647,-1.350676
415,0.701476,-0.508183,0.807573,-0.534933,0.957826,0.755929,-0.351647,0.740370
416,-0.204852,-0.493856,0.807573,-0.534933,0.957826,0.755929,-0.351647,0.740370
417,-0.204852,-0.237621,-1.238278,-0.534933,0.957826,0.755929,-0.351647,-1.350676